version: '3'
services:
  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=settler
      - MYSQL_DATABASE=settler
      - MYSQL_USER=settler
      - MYSQL_PASSWORD=settler
    ports:
      - '8788:3306'
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/1.sql
volumes:
  db_data:
    driver: local
