server:
  port: 8080
  display-name: 'Settler'

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: @settler.db.url@
    username: @settler.db.user@
    password: @settler.db.password@
    test-on-borrow: true
    validation-query: SELECT 1
    validation-interval: 5000
  mail:
    host: @settler.mail.host@
    username: @settler.mail.username@
    password: @settler.mail.password@

  jpa:
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
  http:
    multipart:
      max-file-size: 50Mb
      max-request-size: 50Mb

quartz:
  enabled: false

liquibase:
  change-log: classpath:/db/changelog/db.changelog-master.xml
  enabled: true
  contexts: @settler.db.contexts@

settler:
  mail:
    from-title: Settler
    from-address: settler@dev.morecraft.pl